### ISSUE TITLE
AppArmor can't start under Ubuntu 14.10

### ISSUE THREAD

**Issue by pchaigno** [awailly/cis-ubuntu-ansible#10]
The idempotence test fails under Ubuntu Desktop 14.10 (in a VM). It looks like AppArmor can't start (after at least 3 executions):

```
TASK: [cis | 4.5 Activate AppArmor (start) (Scored)] ************************** 
changed: [192.168.1.20]
```

Here's what I get when I try to start AppArmor:

```
$ sudo service apparmor start 2> /dev/null ; echo $?
apparmor stop/waiting
0
```

**Comment by awailly** [comment]
It seems to be a known bug (https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/1387220) and the good way to do it is with the following command

```
sudo start apparmor ACTION=restart
```

However, it is strange that it works flawlessly on 15.04.

**Comment by pchaigno** [comment]
> However, it is strange that it works flawlessly on 15.04.

I now have the same issue on Ubuntu 15.04 :/
Anything we can do?

**Comment by awailly** [comment]
What is your ansible version ?

**Comment by pchaigno** [comment]
1.9.1, I'll update and test again.

**Comment by pchaigno** [comment]
@awailly Same error with the updated version (`1.9.2`) :/
