### ISSUE TITLE
Provide variables for all of 7.1

### ISSUE THREAD

**Issue by memelet** [awailly/cis-ubuntu-ansible#103]
7.1.1 Disable IP Forwarding sets net.ipv4.ip_forward=0. But this pretty much breaks docker. I don't know why I just ran into this today and not many months ago (could be that I have moved running CIS at the end of playbooks): 

I would really like to disable a few of the 7.1's. This exclusion really should be configured in the playbook and not left for someone to remember to add --exclude-tags. Using tags for exclusion really does not work since there is no way to set tags programmatically.

My first thought was to change from:

```
    tags:
      - section7
      - section7.1
      - section7.1.2
      - section7.1.2.1
```

To

```
    when: >-
      (section7 | default(true) | bool) and
      (section7_1 | default(true) | bool) and
      (section7_1_2 | default(true) | bool) and
      (section7_1_2_1 | default(true) | bool)
```

But that is really messy and a huge change. Besides the tags would still be needed.

So I guess what I want to propose is to define variables for the sysctl values with defaults as they are now:

```
  - name: 7.1.2.1 Disable Send Packet Redirects (Scored)
    sysctl: >
      name=net.ipv4.conf.all.send_redirects
      value="{{ net.ipv4.conf.all.send_redirects }}"
      state=present
```

But when the value is overridden then the node is not in compliance with CIS. But really this playbook does not actually audit anyway. 

I need this change at least for some of these just to get my systems working again. Unless I am mistaken about docker needing

```
  $ sysctl net.ipv4.conf.all.forwarding=1
```

(https://docs.docker.com/engine/userguide/networking/default_network/container-communication/)

Thoughts?

**Comment by awailly** [comment]
Not sure for docker, but making the step configurable is a nice improvement. I will merge the #104 to fix this.

**Comment by awailly** [comment]
@memelet if the PR was enough, feel free to close the issue. If this was more a brain storming about having the whole 7.1 section configurable, tell me. This will require more changes to keep the process simple.
