### ISSUE TITLE
Ubuntu 16.04 compatibility

### ISSUE THREAD

**Issue by janekolszak** [awailly/cis-ubuntu-ansible#112]
Awesome project! Thank you so much for providing this!

Is it ready for Ubuntu 16.04?

**Comment by awailly** [comment]
Thank you! Last time I checked, CIS did not offer 16.04 as a supported OS. Did it change?

**Comment by pchaigno** [comment]
@janekolszak It should work on Ubuntu 16.04, but it will apply CIS Ubuntu 14.04 hardening rules.

**Comment by truongsinh** [comment]
@awailly @pchaigno yes, it changed, CIS offered 16.04 now, should this ticket be reopened?
