### ISSUE TITLE
The 6.15.2 recommendation is not met when AIDE is set to be installed

### ISSUE THREAD

**Issue by cpliakas** [awailly/cis-ubuntu-ansible#114]
After running this role and auditing the results with the [The CIS-CAT Benchmark Assessment Tool](https://benchmarks.cisecurity.org/downloads/audit-tools/#cis-cat), I noticed that the `6.15 Configure Mail Transfer Agent for Local-Only Mode` assessment was failing. After digging in, it seems that AIDE has a dependency on an MTA, which in Ubuntu defaults to Postfix. See https://ubuntuforums.org/showthread.php?t=1448220 for more details.

If this role's `use_aide` variable is set to `True`, which is the default value, then AIDE will install Postfix if it isn't already installed. This is a problem because the `6.15.2 Configure Mail Transfer Agent for Local-Only Mode (Scored)` task is run before AIDE (and as a result, postfix) is installed, and the default configuration file is used which sets the `inet_interfaces = all` parameter. This is against CIS's recommendation.

The easy workaround is to install postfix before running this role so that the  `6.15.2 ...` task can make its changes, however I didn't know if there was a clean way to ensure AIDE is installed prior to running the `6.15.2 ...` task.

Thanks!
Chris

**Comment by awailly** [comment]
Nice catch. If we do the task AIDE task before the `6.15.2` one, will it configure the MTA according to the tool? I remember having to deal with similar issues, and that's why we had to modify the order of several tasks.

**Comment by cpliakas** [comment]
Yes, if the AIDE task is run before the `6.15.2` one then the MTA is correctly configured. I am more than happy to do the leg work and submit a PR if I can get some guidance on how you envision this happening. Thanks for the response!

**Comment by pchaigno** [comment]
I'll launch some tests on branch [`invert-sections-6-8`](https://github.com/awailly/cis-ubuntu-ansible/tree/invert-sections-6-8) to see how we can reorder that exactly.

**Comment by pchaigno** [comment]
@cpliakas Could you check that [this change](https://github.com/awailly/cis-ubuntu-ansible/commit/b6dd10dbe61de1a7688df281b75b0db656ade942) fixes the issue for you?

**Comment by cpliakas** [comment]
@pchaigno Yes! Works perfectly for me.
