### ISSUE TITLE
Missing PAM module in Raspbian

### ISSUE THREAD

**Issue by pchaigno** [awailly/cis-ubuntu-ansible#14]
After the execution of the Ansible playbook on a Raspbian, my logs fill up with:

```
May 17 08:43:48 localhost sudo: pam_unix(sudo:session): session closed for user root
May 17 08:43:36 localhost sudo: PAM unable to dlopen(pam_cracklib.so): /lib/security/pam_cracklib.so: cannot open shared object file: No such file or directory
May 17 08:43:36 localhost sudo: PAM adding faulty module: pam_cracklib.so
```

**Comment by pchaigno** [comment]
The default file doesn't even contain [`pam_cracklib.so`](https://github.com/awailly/cis-ubuntu-ansible/blob/00b0dd0d78010c93b01bf0dd630c6b1f368b4b51/tasks/section_09_level1.yml#L126)

Looks like `lineinfile` adds the new line at the end of the file if the regexp is not matched...

**Comment by awailly** [comment]
I have to check if the libpam-cracklib is available on Raspbian, if the path is `/lib/security` and if the package is already installed on Ubuntu.

**Comment by pchaigno** [comment]
> if the libpam-cracklib is available on Raspbian

It's available but not installed by default.
