### ISSUE TITLE
Incorrect path

### ISSUE THREAD

**Issue by 88lexd** [awailly/cis-ubuntu-ansible#142]
This task has the incorrect path. This needs to be changed to /etc/cron.d

  - name: 5.1.7 Ensure permissions on /etc/cron.d are configured (Scored)
    file:
      path: **/etc/cron.monthly**
      state: directory
      owner: root
      group: root
      mode: 0600

    tags:
      - section5
      - section5.1
      - section5.1.7

**Comment by awailly** [comment]
Thanks! Why did you close it?

**Comment by 88lexd** [comment]
No probs! 

Was looking at this fork so thought I needed to raise the issue on that instead.. :)
https://github.com/grupoversia/cis-ubuntu-ansible/blob/master/tasks/section_05_level1.yml
