### ISSUE TITLE
Warn about large amout of generated logs

### ISSUE THREAD

**Issue by awailly** [awailly/cis-ubuntu-ansible#16]
The auditd configuration may generate a large amount of logs locally if no remote server log is configured. Add an option to warn about that.

**Comment by paskl47** [comment]
According to CIS, remote syslog server is mandatory (cf. 8.2.5 Configure rsyslog to Send Logs to a Remote Log Host). Maximum size of the audit log file is defined in 8.1.1.1 (Configure Audit Log Storage Size).

**Comment by awailly** [comment]
Thus it is a bug if the Maximum Log Size is defined and the log size is higher than the limit. Please check that the limit is correctly defined and that the filesystem cannot be filled.

**Comment by paskl47** [comment]
Normally, auditd will hold 4 logs of maximum log file size before deleting older log files. So if the MMaximum Log Size is defined to 200 Mb, then the system may hold 800 Mb of log.

**Comment by awailly** [comment]
Ok, the bug was related to syslog (https://bugs.launchpad.net/ubuntu/+source/rsyslog/+bug/1366261) and not to auditd. I thing we should rename the Maximum Log Size variable to include "audit". It is misleading.

**Comment by awailly** [comment]
There was an underlying bug in the CIS order that prevented the default auditd.conf file to be created. The default location was thus rsyslog. Fixed in 6fbd5aabf88c112dc9d02182ab5b3810a8682d5e. Please change variable name and close the issue!

**Comment by awailly** [comment]
Fixed with 3b58edb61a93802078f9d7ae7dada5192e10ed30
