### ISSUE TITLE
Missing argument for mount module

### ISSUE THREAD

**Issue by pchaigno** [awailly/cis-ubuntu-ansible#17]
When enabling `partitioning`:
(Ubuntu Desktop 14.04 in a VM)

```
TASK: [cis | 2.6 Bind Mount the /var/tmp directory to /tmp (Scored)] ********** 
failed: [127.0.0.1] => {"failed": true}
msg: missing required arguments: fstype

FATAL: all hosts have already failed -- aborting
```

**Comment by awailly** [comment]
Please check if commit 737795d6fa901a9c52fff644e6ca865774ed4540 fixes the issue.

**Comment by pchaigno** [comment]
Nop, `2.2 - 4` is failing now:

```
TASK: [cis | 2.2 - 4 Set nodev, nosuid, noexec option for /tmp Partition (Scored)] *** 
failed: [127.0.0.1] => {"failed": true}
msg: missing required arguments: src,fstype

FATAL: all hosts have already failed -- aborting
```

EDIT: I don't get why it didn't fail before...

**Comment by awailly** [comment]
This is related to the commit de48cff7bfb802421385246ef9338dbc4fa4bb27 where you fixed the boolean value for "partitioning". The tests were skipped otherwise

**Comment by pchaigno** [comment]
I don't think so because I fixed the issue with the boolean value locally before finding this issue.

**Comment by awailly** [comment]
And you set "partitioning: True" in main.yml ? At least, this is the answer of why travis is still building.

**Comment by pchaigno** [comment]
Yep (see the first line in the first post ;)
It's as if it did `2.6` before doing `2.2 - 4` :scream:
