### ISSUE TITLE
Error when partitioning with tmp not in a separate partition

### ISSUE THREAD

**Issue by pchaigno** [awailly/cis-ubuntu-ansible#23]
When partitioning with `/tmp` in a shared partition. Should we leave it like this or should it skip this one? 

```
TASK: [cis | 2.2 - 4 Set nodev, nosuid, noexec option for /tmp Partition (Scored)] *** 
failed: [127.0.0.1] => {"failed": true}
msg: Error mounting /tmp: mount: /tmp is not a block device


FATAL: all hosts have already failed -- aborting
```

**Comment by pchaigno** [comment]
@awailly Have you ever tried to run the playbook on a VM with a separate partition for `/tmp`?

**Comment by sabriedd** [comment]
That was planned 2 weeks ago before i went on holidays. So, let me try to pop a VM with the required partitioning and i'll keep you informed

**Comment by pchaigno** [comment]
@SpoonBoy Great! Thanks!

**Comment by awailly** [comment]
No I didn't, @SpoonBoy is in charge of the section 2. But I will help if thinks get complicated.

**Comment by sabriedd** [comment]
@pchaigno that might be fixed now, if you could test.

**Comment by pchaigno** [comment]
Same error on my side :/ (with shared partition for `/tmp`)
Looks like `2.2 - 4` wasn't changed in 50cad8d...

**Comment by sabriedd** [comment]
what is your actual setup ? (when you say "shared partition" does it mean shared folder between host and guest ?)
could you send the output of the `mount` command ?
For me, using Ubuntu 14.04.2 LTS works fine.
before the execution of the playbook :

```
/dev/vdaX on /tmp type ext4 (rw)
```

and after the play :

```
/dev/vdaX on /tmp type ext4 (rw,noexec,nosuid,nodev)
```

**Comment by pchaigno** [comment]
Shared partition means `/tmp` doesn't have its own partition. Sorry if that was unclear.
![df](https://cloud.githubusercontent.com/assets/1764210/7729062/01ed7fde-ff13-11e4-9d92-61fe207f1784.png)

`mount` returns `Error mounting /tmp: mount: /tmp is not a block device`.

**Comment by sabriedd** [comment]
ok, then it is a normal behavior i think. As there is no dedicated partition ... mount will fail. That's why the partitioning option is at false by default.

**Comment by pchaigno** [comment]
Hence my initial question ;)

> Should we leave it like this or should it skip this one?

**Comment by awailly** [comment]
I think you can still mount it if you specify that the /tmp folder should be bind mounted.

Can you try to add the "bind" string to "options" in the ansible `mount` service (section 2.2 - 4) ?

**Comment by pchaigno** [comment]
> Can you try to add the "bind" string to "options" in the ansible mount service (section 2.2 - 4) ?

Yes it works for `2.2 - 4` but then it fails for `2.10`: 

```
TASK: [cis | 2.10 Add nodev Option to /home (Scored)] ************************* 
failed: [127.0.0.1] => {"failed": true}
msg: Error mounting /home: mount: /home not mounted or bad option


FATAL: all hosts have already failed -- aborting
```

<br>

Also, the `bind` option is just a hotfix for this, right? Does that mean we leave it like this for other users? I'm asking just to clarify. It's probably okay since there is the `partitioning` to enable/disable exactly this part of the hardening.

**Comment by awailly** [comment]
I see two solutions here:
- Extend the documentation to reference this issue and give solutions when the user is not able to have a separate partition for /tmp @paskl47 
- Add an explicit variable for bind mounting specific partitions. However this will not setup a secure target @SpoonBoy 

I prefer the first one, the second is more a hotfix as you said.

**Comment by sabriedd** [comment]
According to the CIS rules we are applying, it should be dedicated partition in the fstab.

So, or there is partitioning, then section 2 will pass correctly, or there is not, and section 2 will be skipped.

It is not possible (at least, i didn't manage to do so), using ansible to change how the partitioning is done in a current live system, and have it to reboot properly the next time. That is also why we used boolean values in `default/main.yml`, so the user can decide to apply a section or not, depending on how his system is set up. We can not manage every possible partitioning configuration automatically.

I would consider focusing on other issues, as this one fit to the CIS ?

**Comment by pchaigno** [comment]
> Extend the documentation to reference this issue and give solutions when the user is not able to have a separate partition for /tmp @paskl47

I also think the first one would be a better solution :+1:

**Comment by sabriedd** [comment]
@paskl47 I added the documentation : check cc56553ad3b112f7ebdad27d5bcc7df255755748

**Comment by d3netxer** [comment]
I there a way to automatically create a /tmp partition?
