### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by pchaigno** [awailly/cis-ubuntu-ansible#25]
Currently code coverage is low because Travis test build is very limited (that's mainly the reason why it's so easy to find bugs :p). Some tasks can't be tested because of Travis limitations but many other tasks could be tested if the Travis VM had more "issues".

For instance, Travis didn't find the issue with quotes (#13) because it simply didn't have any [unowned file](https://github.com/awailly/cis-ubuntu-ansible/blob/master/.travis.yml#L14-L15).

So, maybe there should be some first script to add stuff to be fixed to the VM (as in 6f6c6e84cd). This would insure that Travis does run all the commands it can run from the playbook.

Ansible seems [a little light on the testing side](http://docs.ansible.com/test_strategies.html) but maybe there is a way to check the code coverage of a playbook...?

**Comment by awailly** [comment]
Very interesting! What about the coverage being the ratio of changed elements on the total number of tasks ? On the first run I mean.

**Comment by pchaigno** [comment]
Yep, that could probably be a good estimation.

**Comment by sabriedd** [comment]
Well ... Doing this will not work i think, as we're using Boolean values in defautls/main.yml 
Depending on the choice of the one who'll use this ansible playbook, there might be (important) parts of the playbook that wont be played.

**Comment by pchaigno** [comment]
Sure but that's the best we can do. The value computed will evaluate the coverage from Travis only.

**Comment by awailly** [comment]
I am looking for a way to create a HTML badge from the travis result. That way we can have a direct view of the code coverage on the main page of the project. Do you know a tool that can do that ?

**Comment by pchaigno** [comment]
I had the same idea :-)
I checked quickly and didn't find anything. If I don't find anything I'll try to ask the guys from GitHub. Otherwise there's probably a way to do that quickly with Heroku...

**Comment by pchaigno** [comment]
I couldn't find a way to do that other than by using Heroku or with weird hacks that may not even work.
I sent an email to the guys at GitHub to see if they have a better idea.

**Comment by awailly** [comment]
The Heroku think is working? Never used it before.

**Comment by awailly** [comment]
We managed to add travis, drone.io and Docker for automatic testing.
