### ISSUE TITLE
Check the Operating System

### ISSUE THREAD

**Issue by pchaigno** [awailly/cis-ubuntu-ansible#40]
We could check the Operating System (in our case Debian-based) before running the playbook to prevent the user from running it against an unsupported OS.

**Comment by awailly** [comment]
Seems like a straightforward `when: ansible_os_family == "Debian"` will do the trick. Can you try on Raspbian? I will add the line in the role or playbook if working.

**Comment by awailly** [comment]
@pchaigno Did you have time for Raspbian tests ?

**Comment by pchaigno** [comment]
Not yet. I'll need to reinstall it first.

**Comment by awailly** [comment]
Ok awesome. The faster the better, you know that I can't sleep if there are issues opened :)

**Comment by pchaigno** [comment]
You must have had terrible holidays then...

**Comment by awailly** [comment]
I did! And did you test in the meantime?

**Comment by pchaigno** [comment]
Okay, it works for Raspbian too.

I can open a pull request to add it to the instructions in the README (for the roles-ubuntu playbook) but I don't think it's the best place for it.
First, because it should probably be in the source code itself. And secondly, because it doesn't fail saying that this OS family is not supported, it just runs through the whole playbook skipping all tasks :/

**Comment by awailly** [comment]
Yes great, put it into the role directly. However I don't know the good place to add it in the tasks.

**Comment by pchaigno** [comment]
> However I don't know the good place to add it in the tasks.

What about a `main.yml` in `tasks/` that calls a second file with the current content of `main.yml`? That way, we could add all our general conditions (Ansible version and OS family) in the new `main.yml`...

**Comment by awailly** [comment]
I think this solution add an unneeded layer, and I cannot see why it is better than adding it to the main.yml.

**Comment by pchaigno** [comment]
Actually, I'm not even sure the solution I proposed could work.

> I cannot see why it is better than adding it to the main.yml.

I must be missing something because I don't see how we can add a `when` condition in `main.yml` without adding it for each item :/

**Comment by pchaigno** [comment]
Maybe there should be a first task to check the general conditions. That way we can display a proper error message when it fails.
