### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by pchaigno** [awailly/cis-ubuntu-ansible#41]
Creating this issue to list to different things missing in the README. I'll probably turn this into a pull request once we have a stable list of what the README should include/explain.
- [x] Link to readthedocs
- [x] Specific version of Ansible needed (1.9.0.1)
- [x] How to only perform an audit
- [x] What OS are supported
- [x] Option to add to the command line call when a sudo password is required
- [x] Requirements on the targeted machine (ssh, aptitude, python)
- [x] How to tune the stable state
- [x] How to contribute (what contributions are accepted, how to test, etc.), ie. a CONTRIBUTING.md file
- [x] Mention the license at the bottom of the README?

**Comment by awailly** [comment]
It is hard to contribute on this one as I cannot find the branch your are working on. Can we work on the `readme` branch on this repo?

**Comment by pchaigno** [comment]
I haven't started working on this so `readme` is fine :)

**Comment by awailly** [comment]
Partial contribution for the first half of the list.

**Comment by awailly** [comment]
@pchaigno can you check the new README and tell if it matches your expectations?

**Comment by pchaigno** [comment]
:+1: 

Closing in favor of #47.
