### ISSUE TITLE
Change minimum ansible version for galaxy

### ISSUE THREAD

**Issue by awailly** [awailly/cis-ubuntu-ansible#43]
We need at least ansible 1.8, galaxy says 1.6.

**Comment by pchaigno** [comment]
Don't we need exactly 1.9.0.1?

**Comment by pchaigno** [comment]
Could we change [`min_ansible_version: 1.6`](https://github.com/awailly/cis-ubuntu-ansible/blob/master/meta/main.yml#L10) to `ansible_version: 1.9.0.1`?

**Comment by awailly** [comment]
Yes, I just forgot why we can't use 1.8.
