### ISSUE TITLE
Auditd denying access to rsyslogd

### ISSUE THREAD

**Issue by pchaigno** [awailly/cis-ubuntu-ansible#44]
On an Ubuntu 14.04.02, after running the playbook once and restarting:
- `/var/log/audit/audit.log` fills up with `type=AVC msg=audit(1434557031.321:238105): apparmor="DENIED" operation="open" profile="/usr/sbin/rsyslogd" name="/run/utmp" pid=1033 comm=72733A6D61696E20513A526567 requested_mask="r" denied_mask="r" fsuid=101 ouid=0` lines.
- The rsyslog daemon is using 100% of one core.

/cc @paskl47 (who found the bug and left the dirty job of reporting it to the intern... :stuck_out_tongue_winking_eye: )

**Comment by awailly** [comment]
Information about the bug in https://bugs.launchpad.net/ubuntu/+source/rsyslog/+bug/1366261. Weird that rsyslog is not up to date on our system.

**Comment by awailly** [comment]
Patch commited. If you have the problem, turn the flag `send_rsyslog_remote: False` in the defaults/main.yml file. If you need remote rsyslog, setup the IP address in the section 8 task file.
