### ISSUE TITLE
Add docker information in the documentation

### ISSUE THREAD

**Issue by awailly** [awailly/cis-ubuntu-ansible#52]
@pchaigno created a Dockerfile to build a secure instance of an Ubuntu container. Can you add this to the documentation @paskl47 ?

**Comment by pchaigno** [comment]
The Dockerfile actually builds instances for 3 Ubuntu versions and the two last Debian versions (yes, in the same Dockerfile) so I don't think it should be used for anything else than tests...

**Comment by awailly** [comment]
Partially addressed with #58
