### ISSUE TITLE
No update for rsyslog logs location

### ISSUE THREAD

**Issue by pchaigno** [awailly/cis-ubuntu-ansible#56]
The location of the logs isn't updated when applying the playbook twice with different settings.

I ran the playbook once with `send_rsyslog_remote = True`, rebooted and ran it a second time with `send_rsyslog_remote = False`. As a result rsyslog still tries to send the logs remotely.

**Comment by awailly** [comment]
So you have the bug without even changing the `send_rsyslog_remote` value ?

**Comment by pchaigno** [comment]
Uh, that was a typo, I fixed it ;)

**Comment by awailly** [comment]
Oh OK. Yes the tasks are skipped if `send_rsyslog_remote` is false, and do not remove the lines.

**Comment by pchaigno** [comment]
Is that the expected behaviour?
It seems correct for the other options because we don't want to "de-harden" but this one doesn't make things less secure, right?

**Comment by awailly** [comment]
Exactly my point. But it makes the system less secure to remove rsyslog. So I can modify the variable name to `set_rsyslog_remote` to be more correct on the behavior.

**Comment by pchaigno** [comment]
Okay but what about `remote_logs_host_address` then? We should be able to change it, right?

**Comment by awailly** [comment]
Yes, some work needed on 8.2.5.1 and 8.2.5.2 for that.

**Comment by pchaigno** [comment]
> Yes, some work needed on 8.2.5.1 and 8.2.5.2 for that.

Should we do that for the beta or pre-release?

**Comment by awailly** [comment]
Pre-release, this is not mandatory and more an enhancement than a bug.
