### ISSUE TITLE
No warning for the tests "Create Seperate Partition"

### ISSUE THREAD

**Issue by paskl47** [awailly/cis-ubuntu-ansible#60]
For the tests "Create Seperate Partition..." only a message is return, but no test in fstab is performed.
Add a test in fsab and create a warning in logs.

**Comment by sabriedd** [comment]
Yes, as said by @paskl47 it is a more precise way to do.
We could check if partitions are present, ignore errors if they're not, but we could still see those steps are missing in the playbook recap and in the future pdf export.

**Comment by pchaigno** [comment]
:+1: 

> we could still see those steps are missing in the playbook recap and in the future pdf export.

That's an issue for the report generator, don't you think?

**Comment by paskl47** [comment]
Exactly, the report generator will use warnings in logs to generate a report. So, we need to test partition creation in fstab to create log.

**Comment by awailly** [comment]
@paskl47 @SpoonBoy Did you sort it out ? Can you update the `tasks/section_02_level1.yml` file and replace the debug messages with `/etc/fstab` tests ?
