### ISSUE TITLE
12.8 Find Un-owned Files and Directories shell command issue

### ISSUE THREAD

**Issue by tamascsiszarvcc** [awailly/cis-ubuntu-ansible#66]
Hi,

I think I've found an issue in section_12_level1.yml  regarding "12.8 Find Un-owned Files and Directories" section.
In the current version shell command is the following:
df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -nogroup -ls
I think it should be the following:
df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -nouser -ls
If you check 12.8 in the official CIS benchmark they also use "-nouser" option.

Regards,
Tamas

**Comment by awailly** [comment]
Hi,

Very nice finding thank you. I will fix it now, tell me if everything is good on your side then.

**Comment by tamascsiszarvcc** [comment]
You're welcome and also thank you for the awesome tool :). I've checked the fix and it woks fine.
