### ISSUE TITLE
Fails to run on ansible 2.0

### ISSUE THREAD

**Issue by jsharpe** [awailly/cis-ubuntu-ansible#75]
This fails to run with ansible 2.0. Error message below:

fatal: [localhost]: FAILED! => {"failed": true, "reason": "ERROR! this task 'debug' has extra params, which is only allowed in the following modules: command, shell, script, include, include_vars, add_host, group_by, set_fact, raw, meta\n\nThe error appears to have been in '/etc/ansible/roles/awailly.cis-ubuntu-ansible/tasks/check_requirements.yml': line 3, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: Check if OS is Debian-based (we do not support others)\n    ^ here\n"}

**Comment by awailly** [comment]
The current version was not tested against ansible 2.0. I will have a look and keep this issue updated.

**Comment by pchaigno** [comment]
@awailly I started working on this at [`ansible-2.0-compliant`](https://github.com/awailly/cis-ubuntu-ansible/tree/ansible-2.0-compliant); I could use some help. The idempotence test is still failing and I can't figure out why :/

**Comment by awailly** [comment]
I spun up a 14.04 instance with ansible 2.0.0.2.

Summary
- [x] Run one time successfully with ansible > 2.0
- [x] Retro-compatible with <2.0 - Status: WIP
- [x] Run level 2 without errors. Status: Next
- [x] Idempotence - Status: WIP
  - [x] 6.15 - Level 2 known bug, no impact https://github.com/awailly/cis-ubuntu-ansible/blob/5d7873b8c8f29f29b5a16d09695bfc326fbd9cbb/.travis.yml#L30-L33
  - [x] 13.9 - Issue with the `file` module that does not create the file
  - [x] 13.18

**Comment by awailly** [comment]
The bug was due to a directory creation and deletion just after. It will be fixed with ansible 2.0 merging.
