### ISSUE TITLE
question: What might be blocking UDP outbound?

### ISSUE THREAD

**Issue by memelet** [awailly/cis-ubuntu-ansible#81]
I find that after running the playbook the OSSEC agent on the node can no longer contact the OSSEC server on UDP port 1514. 

I'm digging thru all the controls, but if anybody can help me along I would really appreciate it.

**Comment by memelet** [comment]
Well, I think this may be a decoy. I just rebuilt the instance and this time there is no block. Give me a bit and I will close this as noise.

**Comment by awailly** [comment]
Ok, I was not able to reproduce and we are not performing iptables modifications related to UDP that I can remember of. Reopen if you have this again.

**Comment by memelet** [comment]
Confirmed. This was a decoy. Sorry for the noise.

**Comment by awailly** [comment]
No worries.
