### ISSUE TITLE
AppArmor not available on Raspbian

### ISSUE THREAD

**Issue by pchaigno** [awailly/cis-ubuntu-ansible#9]
Here's what happen with a Raspbian:

```
TASK: [cis | 4.5 Activate AppArmor (Scored)] ********************************** 
failed: [192.168.1.11] => {"changed": false, "cmd": ["apparmor_status"], "delta": "0:00:00.280982", "end": "2015-05-13 23:39:45.443618", "failed": true, "failed_when_result": true, "rc": 1, "start": "2015-05-13 23:39:45.162636", "stdout_lines": [], "warnings": []}
stderr: AppArmor not available in kernel.

FATAL: all hosts have already failed -- aborting
```

Good luck fixing this one! :stuck_out_tongue_closed_eyes:

**Comment by awailly** [comment]
The 4.5 Activate AppArmor is tagged as level 2, meaning it has a strong impact on the system. I prefer to setup an option in defaults/main.yml rather than checking for kernel support. It is hard to automate the kernel recompile, usually needing a cross-compile to be efficient.
