### ISSUE TITLE
8.2.4.3 ower/permission change causes auth.log and syslog to not be written to

### ISSUE THREAD

**Issue by memelet** [awailly/cis-ubuntu-ansible#93]
On allI CIS'ed systems I find that /var/log/auth.log and /var/log/syslog are empty. If I change the owner of these files to 'syslog' and restart rsyslog then logs are written.

The task is clearly consistent with the benchmark. So I am confused as to what is missing on my systems.

**Comment by pchaigno** [comment]
While this bug can be fixed with #94, I'd be curious to know what was causing it.

**Comment by memelet** [comment]
Yes, me too. I'm guessing that rsyslog is not run as root?

I'm now using

```
      rsyslog_log_files_group: adm
      rsyslog_log_files_permissions: g+r,g-wx,o-rwx
```

Now rsyslog is again writing to /var/log/*

**Comment by awailly** [comment]
This should be in a comment in the configuration file, as you will not be the only user affected.

For debug, `ps aux | grep rsyslog` but I would be surprised if rsyslog runs as root.
