### ISSUE TITLE
ansible_version.full is not supporting in 2.0.2.0

### ISSUE THREAD

**Issue by bpuri-gpsw** [awailly/cis-ubuntu-ansible#98]
The following condition in check_requirement.yml is not working with latest version of ansible - 2.0.2.0
ansible_version.full | version_compare('1.8', '<')

**Comment by awailly** [comment]
Thanks @bpuri-gpsw, can you provide the error?

**Comment by awailly** [comment]
@pchaigno is trying to reproduce the issue with travis in https://github.com/awailly/cis-ubuntu-ansible/tree/test-ansible-2.0.2.

**Comment by pchaigno** [comment]
@bpuri-gpsw [I can't reproduce](https://travis-ci.org/awailly/cis-ubuntu-ansible/jobs/127192071#L516). The error message could help :smiley:

**Comment by senior-sigan** [comment]
@pchaigno Hello. I got this error message:

```
TASK [awailly.cis-ubuntu-ansible : Check if Ansible version is supported] ******
fatal: [10.40.20.2]: FAILED! => {"failed": true, "msg": "The conditional check '{{ ansible_version.full|version_compare('1.8'' failed. The error was: template error while templating string: unexpected end of template, expected ','.. String: {{ ansible_version.full|version_compare('1.8'"}
    to retry, use: --limit @playbooks/hardening.retry

PLAY RECAP *********************************************************************
10.40.20.2                 : ok=3    changed=0    unreachable=0    failed=1
```

My ansible version is: `2.0.2.0`
Host OS is `Ubuntu 16.04 LTS`
Target OS inside vagrant is `Ubuntu 14.04 LTS`

**Comment by awailly** [comment]
Related to https://github.com/ansible/ansible/issues/15572, but it seems to have been fixed a month ago.

**Comment by memelet** [comment]
I was able to run successfully with 2.1 and 2.1.1-RC

**Comment by awailly** [comment]
@blan4 were you able to run it successfully with 2.1 ?
